# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from contextlib import contextmanager
from contextvars import ContextVar
import io
import json
import os
import re
import ssl
from typing import Callable, Mapping, Optional, Union
from weakref import WeakKeyDictionary

import aiohttp
import aiohttp_retry

from lighter.exceptions import ApiException, ApiValueError

RESTResponseType = aiohttp.ClientResponse

ALLOW_RETRY_METHODS = frozenset({'DELETE', 'GET', 'HEAD', 'OPTIONS', 'PUT', 'TRACE'})
LATENCY_TRACE_DIR_ENV = 'BTCFINE_LATENCY_TRACE_DIR'
RequestTraceObserver = Callable[[str, Mapping[str, object]], None]
_request_trace_observer: ContextVar[Optional[RequestTraceObserver]] = ContextVar(
    'lighter_request_trace_observer', default=None
)
_response_traces = WeakKeyDictionary()


def _notify_trace(observer, phase, fields=None):
    if observer is None:
        return
    try:
        observer(phase, {} if fields is None else fields)
    except Exception:
        return

class RESTResponse(io.IOBase):

    def __init__(self, resp) -> None:
        self.response = resp
        self.status = resp.status
        self.reason = resp.reason
        self.data = None
        trace = _response_traces.pop(resp, None)
        self._trace_observer = None if trace is None else trace[0]
        self._connection_state = 'unknown' if trace is None else trace[1]

    async def read(self):
        if self.data is None:
            try:
                self.data = await self.response.read()
            except Exception:
                _notify_trace(
                    self._trace_observer,
                    'response_body_error',
                    {'connection_state': self._connection_state},
                )
                self._trace_observer = None
                raise
            _notify_trace(
                self._trace_observer,
                'response_body_end',
                {
                    'connection_state': self._connection_state,
                    'response_bytes': len(self.data),
                },
            )
            self._trace_observer = None
        return self.data

    def getheaders(self):
        """Returns a CIMultiDictProxy of the response headers."""
        return self.response.headers

    def getheader(self, name, default=None):
        """Returns a given response header."""
        return self.response.headers.get(name, default)


class RESTClientObject:

    def __init__(self, configuration) -> None:

        # maxsize is number of requests to host that are allowed in parallel
        maxsize = configuration.connection_pool_maxsize

        ssl_context = ssl.create_default_context(
            cafile=configuration.ssl_ca_cert
        )
        if configuration.cert_file:
            ssl_context.load_cert_chain(
                configuration.cert_file, keyfile=configuration.key_file
            )

        if not configuration.verify_ssl:
            ssl_context.check_hostname = False
            ssl_context.verify_mode = ssl.CERT_NONE

        connector = aiohttp.TCPConnector(
            limit=maxsize,
            ssl=ssl_context
        )

        self.proxy = configuration.proxy
        self.proxy_headers = configuration.proxy_headers

        trace_configs = []
        raw_trace_dir = os.environ.get(LATENCY_TRACE_DIR_ENV)
        if raw_trace_dir is not None and raw_trace_dir.strip():
            trace_config = aiohttp.TraceConfig()
            trace_config.on_request_start.append(self._trace_request_start)
            trace_config.on_connection_create_start.append(
                self._trace_connection_create_start
            )
            trace_config.on_connection_reuseconn.append(
                self._trace_connection_reuse
            )
            trace_config.on_request_end.append(self._trace_request_end)
            trace_config.on_request_exception.append(self._trace_request_exception)
            trace_configs.append(trace_config)

        # https pool manager
        self.pool_manager = aiohttp.ClientSession(
            connector=connector,
            trust_env=True,
            trace_configs=trace_configs,
        )

        retries = configuration.retries
        self.retry_client: Optional[aiohttp_retry.RetryClient]
        if retries is not None:
            self.retry_client = aiohttp_retry.RetryClient(
                client_session=self.pool_manager,
                retry_options=aiohttp_retry.ExponentialRetry(
                    attempts=retries,
                    factor=0.0,
                    start_timeout=0.0,
                    max_timeout=120.0
                )
            )
        else:
            self.retry_client = None

    @contextmanager
    def trace_request(self, observer):
        """Attach one task-local, best-effort observer to this HTTP request."""

        if observer is not None and not callable(observer):
            raise TypeError('request trace observer must be callable')
        token = _request_trace_observer.set(observer)
        try:
            yield
        finally:
            _request_trace_observer.reset(token)

    @staticmethod
    async def _trace_request_start(session, trace_config_ctx, params):
        observer = _request_trace_observer.get()
        trace_config_ctx.btcfine_observer = observer
        trace_config_ctx.btcfine_connection_state = 'unknown'
        _notify_trace(observer, 'request_start')

    @staticmethod
    async def _trace_connection_create_start(session, trace_config_ctx, params):
        trace_config_ctx.btcfine_connection_state = 'new'

    @staticmethod
    async def _trace_connection_reuse(session, trace_config_ctx, params):
        trace_config_ctx.btcfine_connection_state = 'reused'

    @staticmethod
    async def _trace_request_end(session, trace_config_ctx, params):
        observer = getattr(trace_config_ctx, 'btcfine_observer', None)
        connection_state = getattr(
            trace_config_ctx, 'btcfine_connection_state', 'unknown'
        )
        _response_traces[params.response] = (observer, connection_state)
        _notify_trace(
            observer,
            'response_headers',
            {
                'connection_state': connection_state,
                'http_status': params.response.status,
            },
        )

    @staticmethod
    async def _trace_request_exception(session, trace_config_ctx, params):
        observer = getattr(trace_config_ctx, 'btcfine_observer', None)
        connection_state = getattr(
            trace_config_ctx, 'btcfine_connection_state', 'unknown'
        )
        _notify_trace(
            observer,
            'request_error',
            {
                'connection_state': connection_state,
                'error_type': type(params.exception).__name__,
            },
        )

    async def close(self):
        await self.pool_manager.close()
        if self.retry_client is not None:
            await self.retry_client.close()

    async def request(
        self,
        method,
        url,
        headers=None,
        body=None,
        post_params=None,
        _request_timeout=None
    ):
        """Execute request

        :param method: http request method
        :param url: http request url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        """
        method = method.upper()
        assert method in [
            'GET',
            'HEAD',
            'DELETE',
            'POST',
            'PUT',
            'PATCH',
            'OPTIONS'
        ]

        if post_params and body:
            raise ApiValueError(
                "body parameter cannot be used with post_params parameter."
            )

        post_params = post_params or {}
        headers = headers or {}
        # url already contains the URL query string
        timeout = _request_timeout or 30

        if 'Content-Type' not in headers:
            headers['Content-Type'] = 'application/json'

        args = {
            "method": method,
            "url": url,
            "timeout": timeout,
            "headers": headers
        }

        if self.proxy:
            args["proxy"] = self.proxy
        if self.proxy_headers:
            args["proxy_headers"] = self.proxy_headers

        # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
        if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
            if re.search('json', headers['Content-Type'], re.IGNORECASE):
                if body is not None:
                    body = json.dumps(body)
                args["data"] = body
            elif headers['Content-Type'] == 'application/x-www-form-urlencoded':
                args["data"] = aiohttp.FormData(post_params)
            elif headers['Content-Type'] == 'multipart/form-data':
                # must del headers['Content-Type'], or the correct
                # Content-Type which generated by aiohttp
                del headers['Content-Type']
                data = aiohttp.FormData()
                for param in post_params:
                    k, v = param
                    if isinstance(v, tuple) and len(v) == 3:
                        data.add_field(
                            k,
                            value=v[1],
                            filename=v[0],
                            content_type=v[2]
                        )
                    else:
                        data.add_field(k, v)
                args["data"] = data

            # Pass a `bytes` or `str` parameter directly in the body to support
            # other content types than Json when `body` argument is provided
            # in serialized form
            elif isinstance(body, str) or isinstance(body, bytes):
                args["data"] = body
            else:
                # Cannot generate the request from given parameters
                msg = """Cannot prepare a request message for provided
                         arguments. Please check that your arguments match
                         declared content type."""
                raise ApiException(status=0, reason=msg)

        pool_manager: Union[aiohttp.ClientSession, aiohttp_retry.RetryClient]
        if self.retry_client is not None and method in ALLOW_RETRY_METHODS:
            pool_manager = self.retry_client
        else:
            pool_manager = self.pool_manager

        r = await pool_manager.request(**args)

        return RESTResponse(r)





